### ISSUE TITLE
Internal Server Error 

### ISSUE THREAD

**Issue by jkunlin** [seagle0128/grip-mode#10]
I am using centaur and Emacs 26.3. After firing the command `grip-mode` on a markdown buffer, the WebKit page shows `internal server error`.
But there is no problem with the `markdow-preview` command (preview using chrome browser).

**Comment by seagle0128** [comment]
See https://github.com/seagle0128/.emacs.d/issues/174.

**Comment by jkunlin** [comment]
By setting ` grip-github-user` and `grip-github-password `, I can now preview in WebKit.
But the page keeps flickering or black when the cursor is in the Markdown buffer.
Besides, it seems that the preview page can't be scrolled down. It will return to the top position immediately.

**Comment by jkunlin** [comment]
Preview using the chrome browser does not have the problem.
There is another problem. The CPU usage of emacs will increase dramatically if I switch to another buffer when the grip-mode is enabled.

**Comment by seagle0128** [comment]
I couldn't reproduce this issue. Please provide the details that are described in the issue template.

**Comment by jkunlin** [comment]
I am sorry, but I can't find the issue template. 
I will provide the following information. Hope it is helpful.

Operating System: Linux Mint 19.3
Emacs version: 26.3
.emacs.d: Centaur commit 683594, the only content in custom-post.el is the setting of `grip-github-user` and `grip-github-password`
Grip: I install it using `sudo pip install grip`
Reproduce: 1. open a markdown file using emacs (gui), run `grip-mode`, then the preview page will appear, but keep flickering. 2. open a terminal, run `emacsclient -n -c -a "" a.cc`. Then emacs will take 100% CPU usage.

The markdown file is as simple as following
```
title
-----
body
```

**Comment by seagle0128** [comment]
Do you have a chance to try 27 or 28? I suspect it's related to the widget feature.

**Comment by jkunlin** [comment]
I have just tried 28 and the problem still exists.
But if I preview using Chrome, everything goes well. I think the issue indeed is related to the widget feature.

**Comment by seagle0128** [comment]
You could disable webkit previews.

```elisp
(setq grip-preview-use-webkit nil)
```

**Comment by jkunlin** [comment]
Fine
