### ISSUE TITLE
Don't support color font ?

### ISSUE THREAD

**Issue by WingDust** [seagle0128/grip-mode#11]
![image](https://user-images.githubusercontent.com/45911286/76204676-cff4c300-6233-11ea-8866-dc231a7665bc.png)

![image](https://user-images.githubusercontent.com/45911286/76204771-fe729e00-6233-11ea-8aad-1ba86996af5a.png)

![image](https://user-images.githubusercontent.com/45911286/76204847-1d713000-6234-11ea-96d4-0d4a2b60b458.png)

**Comment by seagle0128** [comment]
It depends on [grip](https://github.com/joeyespo/grip). Seems it doesn't support. Please inquiry to grip.
