### ISSUE TITLE
Autoscroll support

### ISSUE THREAD

**Issue by famiu** [seagle0128/grip-mode#14]
I was thinking that it'd be great if grip-mode had autoscroll support, so the browser window scrolls alongside the emacs buffer. The markdown-preview-mode browser already implements it.

**Comment by seagle0128** [comment]
The server [Grip](https://github.com/joeyespo/grip) doesn't support sync-scrolling.

**Comment by famiu** [comment]
So it's an issue with grip itself rather than grip-mode? Does that mean it's impossible to implement a scroll sync using grip-mode alone without grip support?

**Comment by seagle0128** [comment]
I don't think it's easy to support this feature. The design is totally different from `markdown-preview-mode`.

**Comment by famiu** [comment]
Should I close this issue then?

**Comment by seagle0128** [comment]
Yes. You can file an issue of `Grip` if possible, then `grip-mode` can be changed accordingly. Again I don't think it's easy to support.
