### ISSUE TITLE
Allow preview of project

### ISSUE THREAD

**Issue by mangkoran** [seagle0128/grip-mode#15]
Currently `grip-mode` only executes `grip` on current file. This creates an issue if the page has local resource, e.g. image. Executing `grip` on project root solves this problem. Could this be added to`grip-mode`? Maybe the main usage of `grip-mode` is to render lightweight readme file, but this could be added as an option.

![image](https://user-images.githubusercontent.com/57625126/116333017-5b009600-a805-11eb-9231-31a96e331d33.png)

**Comment by seagle0128** [comment]
Well, I've gotten the root cause. I need some time to investigate how to address it.

**Comment by mangkoran** [comment]
I still cannot view image after the update. The only noticeable change I can see is the `img` element is now at the center of the page, which is expected as I write `align="center"` in the `div` tag.
![image](https://user-images.githubusercontent.com/57625126/116427451-9f784a00-a876-11eb-9ba1-35087398f6d4.png)
