### ISSUE TITLE
是否能够支持修改预览地址

### ISSUE THREAD

**Issue by antx-code** [seagle0128/grip-mode#19]
* 需求
  - 在公司写需求文档定义的时候，因为时间比较紧急，所以需要边出文档，边让产品做原型，需要不只是本地localhost预览，需要能够同时支持内网访问
 * 方案
   - 是否可以设置方案选择设置为本地访问(localhost)还是内网访问(0.0.0.0)

**Comment by seagle0128** [comment]
Upgrade to the latest version and try
```elisp
(setq grip-preview-host "0.0.0.0")
```

**Comment by antx-code** [comment]
Thx~
