### ISSUE TITLE
grip-binary-path or grip-mode-binary-path?

### ISSUE THREAD

**Issue by undes1red** [seagle0128/grip-mode#2]
I installed grip with option '--user' which caused Emacs could't find grip by itself. So I put this line into my settings following the guideline but it didn't work.
```lisp
(setq grip-mode-binary-path "/home/stepinslience/.local/bin/grip")
```
I made a change by replacing `grip-mode-binary-path` with `grip-binary-path` and it works.
```lisp
(setq grip-binary-path "/home/stepinslience/.local/bin/grip")
```

**Comment by seagle0128** [comment]
Thanks! The README has been updated.
