### ISSUE TITLE
GitHub API what for?

### ISSUE THREAD

**Issue by buhtz** [seagle0128/grip-mode#26]
Hi,

from your README it is not clear for me why your application can use GitHub API. For what? It is a markdown editor. It is totally unclear how GitHub can help here. What is the feature behind it?

Maybe you can improve your README/FAQ with that info.

Kind
Christian
[ox-gfm](https://github.com/larstvei/ox-gfm)

**Comment by seagle0128** [comment]
Please refer to https://github.com/joeyespo/grip.

>Grip is a command-line server application written in Python that uses the [GitHub markdown API](http://developer.github.com/v3/markdown) to render a local readme file. The styles and rendering come directly from GitHub, so you'll know exactly how it will appear. Changes you make to the Readme will be instantly reflected in the browser without requiring a page refresh.

**Comment by buhtz** [comment]
Again. Two sentences would have been enough.

This is also a security issue. Do grip or your package do send the markdown to the Microsoft GitHub servers?
In that case there should be  big fat warning about it.

**Comment by seagle0128** [comment]
Your question is to [grip](https://github.com/joeyespo/grip), I think.
 `grip-mode` is just a wrapper, no guarantees for security issue of `grip`.
