### ISSUE TITLE
Rendered preview without margins

### ISSUE THREAD

**Issue by buhtz** [seagle0128/grip-mode#27]
When grip-mode preview the md file with Firefox it looks like this where you see a quit big border/margin around the original document.

Is it somehow possible to render the md file as it is big white without a border, the filename on top and without the grey box?

![grafik](https://user-images.githubusercontent.com/11861496/210803928-ecb782b2-ff48-4d38-ad4c-a07e82c2eb11.png)

**Comment by seagle0128** [comment]
Sorry! Should this request be for [grip](https://github.com/joeyespo/grip) and/or [GitHub API](http://developer.github.com/v3/markdown)?

**Comment by buhtz** [comment]
I don't know. If you would better document your project and how it interacts with other components the user could decide himself.
