### ISSUE TITLE
Enable MathJax 

### ISSUE THREAD

**Issue by jaghili** [seagle0128/grip-mode#29]
Dear @seagle0128,

thank you for your package, I am trying to use it as a Markdown live preview in the browser. 

It seems to work fine, but i'd like to enable maths formulas during the preview, the formulas are not translated at all, they are left between `$$...$$` or `$...$` in the html.

I don't see any mathjax/katex script in the html source. I guess a first possibility is to add it inside `<head>` of the html template, I guess it is in `/usr/lib/python3.11/site-packages/grip/templates/` but i am not sure how to do it properly.

Do you have any idea? 

Thanks !

**Comment by seagle0128** [comment]
It seems a feature requirement for `grip` engine itself. Please file an issue there.
