### ISSUE TITLE
Wrong buffer being rendered

### ISSUE THREAD

**Issue by mrcnski** [seagle0128/grip-mode#3]
If I have multiple windows open, `M-x grip-mode` seems to detect the first one I had open instead of the one currently in focus. Note that I use eyebrowse. Am willing to help debug this if needed.

Also, a weird thing happened. I had my `init.el` open in a non-focused window. I called `grip-mode` on a Markdown file in the focused window. It tried to render my `init.el`, and when I killed the buffer for `init.el`, the file was removed from disk as well. I've never something like this happen before so I'm assuming it's due to this package.

**Comment by seagle0128** [comment]
Please test the latest version. Thanks!
