### ISSUE TITLE
New binary that does not require Github API usage

### ISSUE THREAD

**Issue by ChetanKoneru** [seagle0128/grip-mode#30]
I stumbled upon this rust project that does not use GitHub API.
It is a command line utility and can integrate to nicely to grip-mode 

https://github.com/immanelg/mdopen

**Comment by seagle0128** [comment]
I review the PR, and add one comment. And, I also notice `mdopen` supports browser itself, and doesn't support webkit preview.

**Comment by ChetanKoneru** [comment]
closing this in favor of #31
