### ISSUE TITLE
Instant Org preview ?

### ISSUE THREAD

**Issue by fbob** [seagle0128/grip-mode#4]
It looks like I have to save the org file *each time* I want to preview it as you said in your limitations: "Need to save the buffer before rendering and previewing."

So to me it's not an instant preview or am I missing something here. Is it a present time only limitation ?
Many thanks for your feedback.

**Comment by seagle0128** [comment]
Yeah, I am implementing this feature: instant preview without saving the buffer. But it seems bad performance so far. I am testing, and please stay tuned.

**Comment by seagle0128** [comment]
Already commit 24e9f8e2bde5360b5a4caed6784892025677aba4.

**Comment by fbob** [comment]
Great :+1:

**Comment by seagle0128** [comment]
I made a change for the behavior of org preview. You have to save to preview due to the performance issue.
