### ISSUE TITLE
Creating file with prefix: No such file or directory

### ISSUE THREAD

**Issue by mrcnski** [seagle0128/grip-mode#6]
Hi, looks like I'm getting an error caused by the latest commit (https://github.com/seagle0128/grip-mode/commit/514c090f560af3593bcaa9d881404b6ef8a007c7):

```
Creating file with prefix: No such file or directory, /var/folders/gw/053czpm957z2rq6k8xqvnxx00000gn/T/QA/README.md
```

The problem seems to be that `QA` does not exist in that directory. It should be created first.

(This could be caused by my uniquify settings, which force the buffer name to always include both the directory and the filename:

```elisp
;; Use a sensible mechanism for making buffer names unique.
(require 'uniquify)
(setq uniquify-buffer-name-style 'forward
      uniquify-min-dir-content 1
      uniquify-strip-common-suffix nil
      )
```

so the name of the buffer in question is `QA/README.md`. I guess another solution would be to strip the buffer name of slashes.)

**Comment by seagle0128** [comment]
True. It's caused by `uniquify-buffer-name-style`. I will try to address it.
