### ISSUE TITLE
Error - Grip mode disabled in current buffer

### ISSUE THREAD

**Issue by ChetanKoneru** [seagle0128/grip-mode#7]
I have disabled grip-mode in a org mode file initially, when I try to enable grip-mode in org file by `M-x grip-mode` emacs give me a error 

`Grip mode disabled in current buffer`

This happen even after restarting emacs.How do I enable grip-mode after I disabling. 

looks like there is also an issue with `ox-md` as I am getting when trying enter grip-mode from org file -
`Symbol’s function definition is void: org-make-tag-string`

**Comment by seagle0128** [comment]
I did testings just now and it worked well on my local env.
Could you please provide more details?

**Comment by ChetanKoneru** [comment]
> I did testings just now and it worked well on my local env.
> Could you please provide more details?

I am not sure, if it has a conflict with `https://github.com/alphapapa/org-sticky-header` package

I am also getting the error below in messages buffer when I try to run grip-mode

```
Error during redisplay: (eval (progn (setq org-sticky-header-stickyline (propertize (org-sticky-header--fetch-stickyline) (quote keymap) org-sticky-header-keymap)) (list (propertize " " (quote display) (quote ((space :align-to 0)))) (quote org-sticky-header-stickyline)))) signaled (wrong-type-argument stringp nil) [31 times]

```

**Comment by ChetanKoneru** [comment]
> > I did testings just now and it worked well on my local env.
> > Could you please provide more details?
> 
> I am not sure, if it has a conflict with `https://github.com/alphapapa/org-sticky-header` package
> 
> I am also getting the error below in messages buffer when I try to run grip-mode
> 
> ```
> Error during redisplay: (eval (progn (setq org-sticky-header-stickyline (propertize (org-sticky-header--fetch-stickyline) (quote keymap) org-sticky-header-keymap)) (list (propertize " " (quote display) (quote ((space :align-to 0)))) (quote org-sticky-header-stickyline)))) signaled (wrong-type-argument stringp nil) [31 times]
> ```

**Update**

I have figured out the error. Looks like few of the org-mode packages like `ox-md` disappeared from my config dir.
That was causing errors.
like above and https://github.com/seagle0128/.emacs.d/issues/129
I have fixed it.



 Thanks for your time
