### ISSUE TITLE
grip-mode install error

### ISSUE THREAD

**Issue by WingDust** [seagle0128/grip-mode#9]
![image](https://user-images.githubusercontent.com/45911286/75085780-9fd8cf00-5567-11ea-8395-0e539e203a24.png)

![image](https://user-images.githubusercontent.com/45911286/75085802-d878a880-5567-11ea-874d-997a58317fdc.png)

**Comment by seagle0128** [comment]
`M-x package-refresh-contents`.

**Comment by WingDust** [comment]
thanks
